
name: Docker build and push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push camera_snapshots
      uses: docker/build-push-action@v3
      with:
        ssh: default
        file: ./docker/Dockerfile
        context: .
        push: ${{startsWith(github.ref, 'refs/tags/')}}
        tags: | 
          ghcr.io/roieg/camera_snapshots:latest
          ghcr.io/roieg/camera_snapshots:${{ github.ref_name }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

